INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Szymon', 'Nowak', 'MALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Anna', 'Kowalska', 'FEMALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Piotr', 'Nowakowski', 'MALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Joanna', 'Kowalewska', 'FEMALE');

INSERT INTO ADDRESS (CITY, STREET) VALUES ('Poznan', 'Mickiewicza');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Dublin', 'Dorset');

INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (1,1);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (2,2);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (3,1);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (4,2);

INSERT INTO TODO (NAME, DESCRIPTION, STATUS) VALUES ('Kupic chleb', 'w tesco', 'IN_PROGRESS');
INSERT INTO TODO (NAME, DESCRIPTION, STATUS) VALUES ('Posprzatac', 'kuchnia', 'NEW');

